Feature: A new customer needs to register a profile with the banking system.

  Scenario Outline: As a new customer, I input the needed information incorrectly to register a profile.
    Given I am on the login page
    When  I click the register button in the navigation bar
    When  I input <first_name> in the register first name input
    When  I input <last_name> in the register last name input
    When  I input <email> in the register email input
    When  I input <password> in the register password input
    When  I input <confirmation_password> in the register confirmation password input
    When  I input <phone_number> in the register phone number input
    When  I input <street_address> in the register street address input
    When  I input <city> in the register city input
    When  I input <state> in the register state input
    When  I input <zip_code> in the register zip code input
    When  I click the register button
    Then  I should see a toast notification saying <expected_toast_text>

    Examples:
      | first_name                                                                 | last_name                                                                  | email                                                                      | password                                                                   | confirmation_password                                                      | phone_number                                                               | street_address                                                             | city  | state | zip_code | expected_toast_text                                                            |
      | N/A                                                                        | last                                                                       | first@email.com                                                            | first                                                                      | first                                                                      | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The first name field cannot be left empty, please try again!                   |
      | this is too long and so it should fail and raise the desired error message | last                                                                       | first@email.com                                                            | first                                                                      | first                                                                      | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The first name field cannot exceed 36 characters, please try again!            |
      | first                                                                      | N/A                                                                        | first@email.com                                                            | first                                                                      | first                                                                      | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The last name field cannot be left empty, please try again!                    |
      | first                                                                      | this is too long and so it should fail and raise the desired error message | first@email.com                                                            | first                                                                      | first                                                                      | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The last name field cannot exceed 36 characters, please try again!             |
      | first                                                                      | last                                                                       | N/A                                                                        | first                                                                      | first                                                                      | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The email field cannot be left empty, please try again!                        |
      | first                                                                      | last                                                                       | this is too long and so it should fail and raise the desired error message | first                                                                      | first                                                                      | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The email field cannot exceed 60 characters, please try again!                 |
      | first                                                                      | last                                                                       | first@email.com                                                            | N/A                                                                        | first                                                                      | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The password field cannot be left  empty, please try again!                    |
      | first                                                                      | last                                                                       | first@email.com                                                            | this is too long and so it should fail and raise the desired error message | first                                                                      | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The password field cannot exceed 36 characters, please try again!              |
      | first                                                                      | last                                                                       | first@email.com                                                            | first                                                                      | N/A                                                                        | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The confirmation password field cannot be left empty, please try again!        |
      | first                                                                      | last                                                                       | first@email.com                                                            | first                                                                      | this is too long and so it should fail and raise the desired error message | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The confirmation password field cannot exceed 36 characters, please try again! |
      | first                                                                      | last                                                                       | first@email.com                                                            | first                                                                      | incorrect                                                                  | 1234567890                                                                 | 123 First St                                                               | First | OK    | 73072    | The passwords do not match, please try again!                                  |
      | first                                                                      | last                                                                       | first@email.com                                                            | first                                                                      | first                                                                      | N/A                                                                        | 123 First St                                                               | First | OK    | 73072    | The phone number field cannot be left empty, please try again!                 |
      | first                                                                      | last                                                                       | first@email.com                                                            | first                                                                      | first                                                                      | this is too long and so it should fail and raise the desired error message | 123 First S                                                                | First | OK    | 73072    | The phone number field cannot exceed 12 characters, please try again!          |
      | first                                                                      | last                                                                       | first@email.com                                                            | first                                                                      | first                                                                      | 1234567890                                                                 | this is too long and so it should fail and raise the desired error message | First | OK    | 73072    | The address field cannot exceed 60 characters, please try again!               |
      | first                                                                      | last                                                                       | first@email.com                                                            | first                                                                      | first                                                                      | 1234567890                                                                 | N/A                                                                        | N/A   | N/A   | N/A      | The address field cannot be left empty, please try again!                      |
      | test                                                                       | customer                                                                   | test@email.com                                                             | work                                                                       | work                                                                       | 1234567890                                                                 | 123 This Street                                                            | City  | OK    | 73093    | A customer already exists with this username, please log in!                   |

  Scenario Outline: As a new customer, I successfully input the needed information to register a profile.
    Given I am on the login page
    When  I click the register button in the navigation bar
    When  I input <first_name> in the register first name input
    When  I input <last_name> in the register last name input
    When  I input <email> in the register email input
    When  I input <password> in the register password input
    When  I input <confirmation_password> in the register confirmation password input
    When  I input <phone_number> in the register phone number input
    When  I input <street_address> in the register street address input
    When  I input <city> in the register city input
    When  I input <state> in the register state input
    When  I input <zip_code> in the register zip code input
    When  I click the register button
    Then  I should see a toast notification saying <expected_toast_text>

    Examples:
      | first_name | last_name | email           | password | confirmation_password | phone_number | street_address | city  | state | zip_code | expected_toast_text                          |
      | first      | last      | first@email.com | first    | first                 | 123-456-7890 | 123 First St   | First | OK    | 73072    | Profile successfully created, please log in! |
